#version 450

layout (rgba16f, set = 0, binding  = 0) uniform image2D drawImage;
layout (local_size_x = 1, local_size_y = 1) in;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(drawImage);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

        if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
        {
            color.x = float(texelCoord.x)/(size.x);
            color.y = float(texelCoord.y)/(size.y);
            color.z = float(texelCoord.x + texelCoord.y)/(size.x - size.y + 0.11);
        }

        imageStore(drawImage, texelCoord, color);
    }
}